"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
import environ 

env = environ.Env() #-->Inicializa la configuración del entorno
env_file = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), '.env')
environ.Env.read_env(env_file)



#*************************DEEFINIMOS LAS VARIABLES QUE USAREMOS**************************************************************
ENVIROMENT = env

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent #Osea -->  BASE_DIR =ECommerceV2.0.0

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure-+!0z%2&=uzc9r&-h$frl3hlefgn*ch2k(ki59o_c_0^x2w%0lb')
#/*************************************************************************************************************/

# Braintree Settings
BT_ENVIRONMENT = env('BT_ENVIRONMENT', default='sandbox')
BT_MERCHANT_ID = env('BT_MERCHANT_ID', default='')
BT_PUBLIC_KEY = env('BT_PUBLIC_KEY', default='')
BT_PRIVATE_KEY = env('BT_PRIVATE_KEY', default='')





# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=True)

# Configuración importante para Windows
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['*'])


# Application definition
DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

PROJECT_APPS=['user', 'user_profile']
ECOMMERCE_APPS=['category','product','cart', 'shipping', 'payment', 'orders', 'reviews', 'wishlist', 'coupons']
THIRD_PARTY_APPS=[
    'corsheaders',
    'rest_framework',
    'djoser',
    'social_django',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'ckeditor',
    'ckeditor_uploader',
    'anymail',
    'storages',
]

INSTALLED_APPS= DJANGO_APPS + PROJECT_APPS + ECOMMERCE_APPS + THIRD_PARTY_APPS

CKEDITOR_CONFIGS={
    'default':{
        'toolbar':'full',
        'autoParagraph':False
    }
}

CKEDITOR_UPLOAD_PATH = "/media/"

MIDDLEWARE = [
    'social_django.middleware.SocialAuthExceptionMiddleware',
    'corsheaders.middleware.CorsMiddleware',

    
    'django.middleware.security.SecurityMiddleware',

    'whitenoise.middleware.WhiteNoiseMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'



#/************************************Para los templates (conectar el template  )****************************/
FRONTEND_DIR = BASE_DIR / 'frontend'
REACT_BUILD_DIR = FRONTEND_DIR / 'build'

if os.path.exists(REACT_BUILD_DIR / 'static'):
    STATICFILES_DIRS = [
        REACT_BUILD_DIR / 'static',
    ]
else:
    STATICFILES_DIRS = []

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [REACT_BUILD_DIR] if os.path.exists(REACT_BUILD_DIR) else [],  # Utiliza el build de React para servir index.html si existe
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

#***************************************CONFIGURACIÓN DE LAS BASE DE DATOS****************************************/

if env('DATABASE_URL', default=None):
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.config(default=env('DATABASE_URL'))
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'mysql.connector.django',
            'NAME': env('DB_NAME', default='local'),
            'USER': env('DB_USER', default='root'), 
            'PASSWORD': env('DB_PASSWORD', default='12alberto!viejoComeSillas/'),
            'HOST': env('DB_HOST', default='localhost'),
            'PORT': env('DB_PORT', default='3306'),
        }
    }

DATABASES["default"]["ATOMIC_REQUEST"]=True

#Las dos siguientes son para que no vaya a haber ningun error de cors o csrf
CORS_ORIGIN_WHITELIST = env.list('CORS_ALLOWED_ORIGINS', default=[
    'http://localhost:3000',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://127.0.0.1:3000',
])

CSRF_TRUSTED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=[
    'http://localhost:3000',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://127.0.0.1:3000',
])

#/*******************************************************************************************************************/
#Acá es una configuración de una forma que nos da django para guardar contraseñas de los usuarios
#Cuestiones de seguridad 
PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
    "django.contrib.auth.hashers.ScryptPasswordHasher",
]



# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR,'static')
STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'backend', 'media')
MEDIA_URL = '/media/'

# --- NEON OBJECT STORAGE / AWS S3 ---
AWS_ACCESS_KEY_ID = env('AWS_ACCESS_KEY_ID', default=None)
if AWS_ACCESS_KEY_ID:
    AWS_SECRET_ACCESS_KEY = env('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = env('AWS_STORAGE_BUCKET_NAME', default='media')
    AWS_S3_ENDPOINT_URL = env('AWS_ENDPOINT_URL_S3')
    AWS_S3_REGION_NAME = env('AWS_REGION')
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    AWS_S3_FILE_OVERWRITE = False
    
    # Optional but highly recommended: Path-style is required by Neon
    AWS_S3_ADDRESSING_STYLE = "path" 
    
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    
    # Tell CKEditor to also upload directly to the bucket
    AWS_LOCATION = ''

if os.path.exists(os.path.join(BASE_DIR, 'frontend', 'build', 'static')):
    STATICFILES_DIRS = [
        os.path.join(BASE_DIR, 'frontend', 'build', 'static')
    ]
else:
    STATICFILES_DIRS = []


#/*************************************************************************************************************/
#Ahora la configuración para el RESTFRAMEWORK
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly'
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 12  
}

AUTHENTICATION_BACKENDS = (
    'user.backends.StatelessGoogleOAuth2',
    'social_core.backends.facebook.FacebookOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)

#Autenticación JWT
SIMPLE_JWT = {
    'AUTH_HEADER_TYPES': ('JWT',),
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=10090),
    'REFRESH_TOKEN_LIFETIME' : timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'AUTH_TOKEN_CLASSES':(
        'rest_framework_simplejwt.tokens.AccessToken',
    )
}

#Para Djoser
DJOSER = {
    'LOGIN_FIELD': 'email',
    'USER_CREATE_PASSWORD_RETYPE': True,
    'USERNAME_CHANGED_EMAIL_CONFIRMATION': True, #que si alguien quiere cambiar su email, debe mandar una confirmación al email actual
    'PASSWORD_CHANGED_EMAIL_CONFIRMATION': True,#que si alguien quiere cambiar su password, debe mandar una confirmación al email actual
    'SEND_CONFIRMATION_EMAIL': True,
    'SET_USERNAME_RETYPE': True,
    'PASSWORD_RESET_CONFIRM_URL': 'password/reset/confirm/{uid}/{token}',
    'SET_PASSWORD_RETYPE': True,
    'PASSWORD_RESET_CONFIRM_RETYPE': True,
    'USERNAME_RESET_CONFIRM_URL': 'email/reset/confirm/{uid}/{token}',
    'ACTIVATION_URL': 'activate/{uid}/{token}',
    'SEND_ACTIVATION_EMAIL': True,
    'SOCIAL_AUTH_TOKEN_STRATEGY': 'djoser.social.token.jwt.TokenStrategy',
    'SOCIAL_AUTH_ALLOWED_REDIRECT_URIS': [
        f"{env('FRONTEND_URL', default='http://localhost:3000')}/login",
        f"{env('FRONTEND_URL', default='http://localhost:3000')}/signup",
        env('FRONTEND_URL', default='http://localhost:3000'),
        'http://localhost:3000/login', 
        'http://localhost:3000/signup',
        'http://127.0.0.1:3000/login',
        'http://127.0.0.1:3000/signup',
        'http://localhost:3000',
        'http://127.0.0.1:3000'
    ],
    'SERIALIZERS': {
        'user_create': 'user.serializers.UserCreateSerializer',
        'user': 'user.serializers.UserCreateSerializer',
        'current_user': 'user.serializers.UserCreateSerializer',
        'user_delete': 'djoser.serializers.UserDeleteSerializer',
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



#/****************************CONECTAR EMAILS*********************************************************************/
AUTH_USER_MODEL = 'user.UserAccount' #Le decimos a Django que el modelo de usuario que vamos a usar es el que acabamos de crear

# Domain for Djoser emails
DOMAIN = '127.0.0.1:3000'
SITE_NAME = 'NitroStore'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
DEFAULT_FROM_EMAIL = env('EMAIL_HOST_USER', default='luisrodrigo1005@gmail.com')
EMAIL_HOST = env('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
EMAIL_PORT = env('EMAIL_PORT', default=587)
EMAIL_USE_TLS = env('EMAIL_USE_TLS', default=True)


# Se agrega esta linea en desarrollo para desactivar CSRF, luego se borra en producción
CSRF_COOKIE_SECURE = False

CORS_ALLOW_HEADERS = [
    'content-type',
    'authorization',
    'x-csrftoken',
    'x-requested-with',
]

CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=[
    "http://localhost:3000",
    "http://127.0.0.1:3000",
])
CORS_ALLOW_CREDENTIALS = True


# Autenticacin Social (OAuth)
AUTHENTICATION_BACKENDS = (
    'user.backends.StatelessGoogleOAuth2',
    'user.backends.StatelessGithubOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = env('GOOGLE_CLIENT_ID', default='')
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = env('GOOGLE_CLIENT_SECRET', default='')
SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = [
    'https://www.googleapis.com/auth/userinfo.email',
    'https://www.googleapis.com/auth/userinfo.profile',
]

SOCIAL_AUTH_GITHUB_KEY = env('GITHUB_CLIENT_ID', default='')
SOCIAL_AUTH_GITHUB_SECRET = env('GITHUB_CLIENT_SECRET', default='')
SOCIAL_AUTH_GITHUB_SCOPE = ['user:email']

# Deshabilitar validacin de estado por sesin
SOCIAL_AUTH_GOOGLE_OAUTH2_STATE_PARAMETER = False
SOCIAL_AUTH_GITHUB_STATE_PARAMETER = False

# Custom Redirect URIs for Stateless OAuth
SOCIAL_AUTH_GITHUB_REDIRECT_URI = env('FRONTEND_URL', default='http://localhost:3000') + '/login'
SOCIAL_AUTH_GOOGLE_OAUTH2_REDIRECT_URI = env('FRONTEND_URL', default='http://localhost:3000') + '/login'
