# Generated by Django 5.2.7 on 2026-09-19 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_date_updated_review_likes_review_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
